# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0002_auto_20160109_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 3, 13, 0)),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentor_end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 3, 14, 0)),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentor_start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 3, 9, 0)),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 3, 10, 0)),
        ),
    ]
